name: commit_message_generation
channels:
  - huggingface
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pytorch==1.7.0
  - pytorch-lightning=1.1.4
  - transformers=4.2.1
  - pip:
    - datasets==1.3.0
    - nltk==3.5
    - rouge-score==0.0.4
    - wandb==0.10.14
    - hydra-core==1.0.5
    - torchmetrics==0.4.1
    - black
    - pytest