name: commit_message_generation
channels:
  - huggingface
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pytorch==1.7.0
  - pytorch-lightning=1.1.4
  - transformers=4.2.1
  - pip:
    - datasets==1.3.0
    - rapidfuzz==2.0.11
    - nltk==3.6.4
    - rouge-score==0.0.4
    - wandb==0.10.14
    - hydra-core==1.0.5
    - sacrebleu==2.0.0
    - torchmetrics==0.4.1
    - isort==5.9.3
    - black==22.3.0
    - pytest==7.1.2