testing: false

dataset_root: raw_data/multilang

context_ratio:
generate_with_history: true
train_with_history: true

encoder_input_type: diff

diff_tokenizer_name_or_path:  # can be provided in model config
encoder_context_max_len: 512  # can be provided in model config

msg_tokenizer_name_or_path:   # can be provided in model config
decoder_context_max_len: 512  # can be provided in model config

preprocessor_conf:
  configuration: default      # can be provided in model config
  default:
    chunksize: 4096
  race:
    chunksize: 4096

train_dataloader_conf:
  batch_size: 16
  num_workers: 4

val_dataloader_conf:
  batch_size: 16
  num_workers: 4

test_dataloader_conf:
  batch_size: 1
  num_workers: 1