dataset:
  dataset_root: raw_data/CleanedJiang
  diff_max_len: 100
  msg_max_len: 30
  train_dataloader_conf:
    batch_size: 16
    shuffle: true
    num_workers: 4
  val_dataloader_conf:
    batch_size: 16
    num_workers: 4
  test_dataloader_conf:
    batch_size: 16
    num_workers: 4
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: train longer encoderdecoder architecture
  project: commit_message_generation
model:
  learning_rate: 1e-4
  reduction: mean
  model_name_or_path: microsoft/codebert-base
trainer:
  gpus: 1
  max_epochs: 2
  limit_val_batches: 10
  limit_test_batches: 10