dataset:
  dataset_root: raw_data/CleanedJiang
  diff_max_len: 100
  msg_max_len: 30
  train_dataloader_conf:
    batch_size: 6
    shuffle: true
    num_workers: 4
  val_dataloader_conf:
    batch_size: 6
    num_workers: 4
  test_dataloader_conf:
    batch_size: 6
    num_workers: 4
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: transpose+pooler lr_5e-5 tf_65
  project: commit_message_generation
model:
  embedding_dim: 768
  hidden_size_decoder: 256
  hidden_size_encoder: 768
  num_heads: 8
  num_layers: 1
  dropout: 0.2
  bridge: true
  teacher_forcing_ratio: 0.65
  learning_rate: 5e-5
  reduction: mean
  model_name_or_path: microsoft/codebert-base
trainer:
  gpus: 1
  max_epochs: 10
  limit_train_batches: 250
  limit_val_batches: 100