dataset:
  dataset_root: raw_data/CleanedJiang
  diff_max_len: 100
  msg_max_len: 30
  encoder_name_or_path: microsoft/codebert-base
  decoder_name_or_path: distilgpt2
  train_dataloader_conf:
    batch_size: 32
    shuffle: true
    num_workers: 4
  val_dataloader_conf:
    batch_size: 32
    num_workers: 4
  test_dataloader_conf:
    batch_size: 32
    num_workers: 4
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: train longer codebert2distilgpt2
  project: commit_message_generation
model:
  learning_rate: 3e-5
  encoder_name_or_path: microsoft/codebert-base
  decoder_name_or_path: distilgpt2
trainer:
  gpus: 1
  max_epochs: 30
  num_sanity_val_steps: 2