dataset:
  dataset_root: placeholder
  train_fname: placeholder
  val_fname: placeholder
  test_fname: placeholder
  train_dataloader_conf:
    batch_size: 1
    num_workers: 16
  val_dataloader_conf:
    batch_size: 1
    num_workers: 16
  test_dataloader_conf:
    batch_size: 1
    num_workers: 16

embedder:
  configuration: bag_of_words
  bag_of_words:
    max_features: 100000
    load_vocab: false
    save_vocab: true
    chunksize: 10000

search:
  configuration: diff
  diff:
    num_neighbors: 5
    num_trees: 10000
    load_index: false

logger:
  args:
    name: placeholder
    project: placeholder
  log_artifact: true
  artifact:
    name: placeholder
    type: placeholder
    table_name: placeholder

