actual_generation: true
dataset:
  dataset_root: raw_data/multilang
  history_max_len: 200
  encoder_name_or_path: raw_data/multilang/diff_tokenizer.json
  decoder_name_or_path: distilgpt2
  with_history: true
  context_ratio: 0.25
  local_rank: 0
  world_size: 1
  history_sep: "\n"
  test_dataloader_conf:
    batch_size: 1
    num_workers: 4
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  id: 28g0hm3j
  project: commit_message_generation
model:
  encoder_decoder: true
  decoder_name_or_path: distilgpt2
trainer:
  gpus: 1
  limit_test_batches: 200
ckpt_path: outputs/2022-04-01/11-53-47/checkpoint/last.ckpt
