actual_generation: true
dataset:
  dataset_root: test_data/python
  history_max_len: 200
  encoder_name_or_path: microsoft/codebert-base
  decoder_name_or_path: distilgpt2
  with_history: true
  context_ratio: 0.25
  local_rank: 0
  world_size: 1
  history_sep: "\n"
  test_dataloader_conf:
    batch_size: 1
    num_workers: 4
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: python 25% in context ('\n' as separator)
  project: commit_message_generation
model:
  encoder_decoder: true
  decoder_name_or_path: distilgpt2
trainer:
  gpus: 1
ckpt_path: artifacts/transformer_with_history_python:v0/epoch=4-step=81318.ckpt
