dataset:
  dataset_root: raw_data/github_data
  history_max_len: 200
  encoder_name_or_path: microsoft/codebert-base
  decoder_name_or_path: distilgpt2
  with_history: true
  local_rank: 0
  world_size: 1
  test_dataloader_conf:
    batch_size: 16
    num_workers: 1
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  group: new metrics
  project: commit_message_generation
model:
  encoder_decoder: true
  decoder_name_or_path: distilgpt2
  actual_generation: false
trainer:
  gpus: 1
ckpt_path: artifacts/full_transformer4_4_best_and_last:v0/epoch=4-step=767653.ckpt
