dataset:
  dataset_root: raw_data/CleanedJiang
  diff_max_len: 110
  msg_max_len: 30
  encoder_name_or_path: microsoft/codebert-base
  train_dataloader_conf:
    batch_size: 32
    shuffle: true
    num_workers: 4
  val_dataloader_conf:
    batch_size: 32
    num_workers: 4
  test_dataloader_conf:
    batch_size: 32
    num_workers: 4
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: codebert + nn
  project: commit_message_generation