actual_generation: true
dataset:
  dataset_root: raw_data/github_data
  history_max_len: 200
  encoder_name_or_path: microsoft/codebert-base
  decoder_name_or_path: distilgpt2
  with_history: true
  context_ratio: 0.1
  local_rank: 0
  world_size: 1
  test_dataloader_conf:
    batch_size: 8
    num_workers: 4
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: test new collators (distilgpt2 with prefix)
  group: new metrics
  project: commit_message_generation
model:
  encoder_decoder: false
  decoder_name_or_path: distilgpt2
trainer:
  gpus: 1
  limit_test_batches: 10
