stage: test

defaults:
  - dataset/default_dataset

wandb_logger:
  project: commit_message_generation

generation_kwargs:
  num_beams: 5
  repetition_penalty: 1.0
  length_penalty: 1.0
  no_repeat_ngram_size: 4
  min_length: 1
  max_length: 15

trainer:
  gpus: 1

model_name: false

model_artifact:
  project: saridormi/commit_message_generation
  artifact_path: last.ckpt
  local_path: artifacts

ckpt_path: placeholder