wandb:
  project: test
  model_name:
  model_config:

  artifact_project: saridormi/commit_message_generation
  input_artifact_name: ${wandb.artifact_project}/${wandb.model_name}_preds:${wandb.model_config}
  input_table_name: ${wandb.model_config}
  metadata_artifact_name: saridormi/commit_message_generation/metadata:latest

input_file: path/to/input/file
max_n_tokens: 15

language: false