wandb:
  project: commit_message_completion
  artifact:
    project: saridormi/commit_message_completion
    name:
    version:
    table_name:

input_file: path/to/input/file
max_n_tokens: 15

language: false
only_short_sequences: false
only_long_sequences: false