defaults:
  - dataset/default_dataset

model:
  learning_rate: 1e-4

wandb_logger:
  project: commit_message_generation
  save_model_as_artifact: true

trainer:
  gpus: 3
  auto_select_gpus: false
  accelerator: ddp
  max_epochs: 5
  precision: 16
  amp_level: O1
  accumulate_grad_batches: 1
  num_sanity_val_steps: 100