defaults:
  - _self_
  - dataset/default_dataset

model:
  learning_rate:
  weight_decay:
  num_warmup_steps: 4000

wandb_logger:
  project: commit_message_completion
  save_model_as_artifact: true

trainer:
  max_epochs: 5
  precision: 16
  amp_backend: native
  accumulate_grad_batches: 1
  num_sanity_val_steps: 100
  gradient_clip_val: 1.0