# @package _group_
embedding_dim: 768
hidden_size_decoder: 256
hidden_size_encoder: 768
num_heads: 8
num_layers: 2
dropout: 0.2
bridge: true
teacher_forcing_ratio: 0.75
learning_rate: 1e-4
model_name_or_path: microsoft/codebert-base