data_processor:
  prompt_max_len: 200
  diff_tokenizer_name_or_path: distilbert-base-cased
  msg_tokenizer_name_or_path: distilgpt2
  preprocessing: false
model:
  encoder_name_or_path: distilbert-base-cased
  decoder_name_or_path: distilgpt2
generation_kwargs:
  early_stopping: True
  num_beams: 5
  num_return_sequences: 1
min_length: 2
max_length: 10