model_kwargs:
  wandb_artifact: commit_message_generation/full_transformer4_4_best_and_last:v0
  tokenizer: microsoft/codebert-base
  opset: 11
  paths:
    seq2seq_model: onnx_utils/data/seq2seq_model
    encoder: onnx_utils/data/encoder
    onnx_encoder: onnx_utils/data/onnx/encoder.onnx
    optimized_onnx_encoder: onnx_utils/data/optimized_encoder.onnx
